[preface]
[[preface]]
== Préface

Le Lightning Network (LN) est un réseau pair-à-pair de deuxième couche qui nous permet d'effectuer des paiements Bitcoin "hors chaîne", c'est-à-dire sans les enregistrer en tant que transactions dans la blockchain Bitcoin.

Le Lightning Network nous offre des paiements Bitcoin sécurisés, bon marché, rapides et beaucoup plus privés, même pour les très petits paiements.

En s'appuyant sur l'idée des canaux de paiements, proposée pour la première fois par l'inventeur de Bitcoin, Satoshi Nakamoto, le Lightning Network est un réseau routé de canaux de paiements où les paiements "sautent" sur un chemin de canaux de paiements de l'expéditeur au destinataire.

L'idée initiale du Lightning Network a été proposée en 2015 dans l'article révolutionnaire "The Bitcoin Lightning Network: Scalable Off-Chain Instant Payments", de Joseph Poon et Thaddeus Dryja. En 2017, un réseau "test" Lightning fonctionnait sur Internet alors que différents groupes construisaient des implémentations compatibles et se coordonnaient pour établir des normes d'interopérabilité. En 2018, le Lightning Network est lancé en "live" et les paiements ont commencé à affluer.

En 2019, Andreas M. Antonopoulos, Olaoluwa Osuntokun et René Pickhardt ont accepté de collaborer pour écrire ce livre. Il semble que nous ayons réussi !

[[intended_audience_sec]]
=== Public visé

Ce livre est principalement destiné aux lecteurs techniques ayant une compréhension des principes fondamentaux de Bitcoin et d'autres blockchains ouvertes.

[role="pagebreak-before less_space"]
[[conventinons_used_sec]]
=== Conventions utilisées dans ce livre

Les conventions typographiques suivantes sont utilisées dans ce livre :

_Italique_:: Indique de nouveaux termes, URL, adresses e-mail, noms de fichiers et extensions de fichiers.

+Largeur fixe+:: Utilisé pour les listings de programmes, ainsi que dans les paragraphes pour faire référence à des éléments de programme tels que des noms de variables ou de fonctions, des bases de données, des types de données, des variables d'environnement, des instructions et des mots-clés.

**`Largeur fixe en gras`**:: Affiche les commandes ou tout autre texte qui doit être saisi littéralement par l'utilisateur.

_++Largeur fixe en italique++_:: Affiche le texte qui doit être remplacé par des valeurs fournies par l'utilisateur ou par des valeurs déterminées par le contexte.

[TIP]
====
Cet élément signifie un conseil ou une suggestion.
====

[NOTE]
====
Cet élément signifie une note générale.
====

[WARNING]
====
Cet élément indique un avertissement ou une mise en garde.
====

[[code_examples_sec]]
=== Exemples de code

Les exemples sont illustrés en Go, C++, Python et en utilisant la ligne de commande d'un système d'exploitation de type Unix. Tous les extraits de code sont disponibles dans le dépôt GitHub dans le sous-répertoire _code_. Forkez le code du livre, essayez les exemples de code ou soumettez des corrections via https://github.com/lnbook/lnbook[GitHub].

Tous les extraits de code peuvent être répliqués sur la plupart des systèmes d'exploitation avec une installation minimale de compilateurs, d'interpréteurs et de bibliothèques pour les langages correspondants. Si nécessaire, nous fournissons des instructions d'installation de base et des exemples étape par étape de la sortie de ces instructions.

Certains des extraits de code et des sorties de code ont été reformatés pour l'impression. Dans tous ces cas, les lignes ont été séparées par une barre oblique inverse (+\+), suivie d'un caractère de saut de ligne. Lors de la transcription des exemples, supprimez ces deux caractères et rejoignez les lignes à nouveau et vous devriez voir des résultats identiques à ceux présentés dans l'exemple.

Tous les extraits de code utilisent des valeurs réelles et des calculs lorsque cela est possible, de sorte que vous pouvez construire d'exemple en exemple et voir les mêmes résultats dans tous les code que vous écrivez pour calculer les mêmes valeurs. Par exemple, les clés privées et les clés et adresses publiques correspondantes sont toutes réelles.

[[using_code_examples_sec]]
=== Utilisation d'exemples de code

Si vous avez une question technique ou un problème d'utilisation des exemples de code, veuillez envoyer un e-mail à l'adresse pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

Ce livre est là pour vous aider à faire votre travail. En général, si un exemple de code est proposé avec ce livre, vous pouvez l'utiliser dans vos programmes et votre documentation. Vous n'avez pas besoin de nous contacter pour obtenir une autorisation, sauf si vous reproduisez une partie importante du code. Par exemple, écrire un programme qui utilise plusieurs morceaux de code de ce livre ne nécessite pas d'autorisation. La vente ou la distribution d'exemples tirés des livres d'O'Reilly nécessite une autorisation. Répondre à une question en citant ce livre et en citant un exemple de code ne nécessite pas d'autorisation. L'incorporation d'une quantité importante d'exemples de code de ce livre dans la documentation de votre produit nécessite une autorisation.

Nous apprécions, mais nous ne demandons pas d'attribution. Une attribution comprend généralement le titre, l'auteur, l'éditeur, l'ISBN et le droit d'auteur. Par exemple : &#x201c;__Maîtriser le Lightning Network__ par Andreas M. Antonopoulos, Olaoluwa Osuntokun et René Pickhardt (O'Reilly). Copyright 2022 aantonop Books LLC, René Pickhardt et uuddlrlrbas LLC, ISBN 978-1-492-05486-3."

__Maîtriser le Lightning Network__ est proposé sous la licence Creative Commons Attribution - Pas d'Utilisation Commerciale - Pas de Modification 4.0 International (CC BY-NC-ND 4.0).

Si vous pensez que votre utilisation d'exemples de code ne respecte pas l'utilisation équitable ou l'autorisation donnée précédemment, n'hésitez pas à nous contacter à l'adresse pass:[<a href="mailto:permissions@oreilly.com">permissions@oreilly.com</a>].

=== Références aux entreprises et aux produits

Toutes les références aux entreprises et aux produits sont destinées à des fins éducatives, de démonstration et de référence. Les auteurs n'approuvent aucune des sociétés pass:[<span class="keep-together">ou produits</span>] mentionnés. Nous n'avons testé le fonctionnement ou la sécurité d'aucun des produits, projets ou segments de code présentés dans ce livre. Utilisez-les à vos risques et périls !

[[addresses_and_transactions_sec]]
=== Adresses et transactions dans ce livre

Les adresses, transactions, clés, codes QR et données de blockchain Bitcoin utilisés dans ce livre sont, pour la plupart, réels. Cela signifie que vous pouvez parcourir la blockchain, regarder les transactions proposées en exemple, les récupérer avec vos propres scripts ou programmes, etc.

Cependant, notez que les clés privées utilisées pour construire les adresses imprimées dans ce livre ont été "brûlées". Cela signifie que si vous envoyez de l'argent à l'une de ces adresses, l'argent sera perdu pour toujours ou (plus probablement) approprié, puisque toute personne qui lit le livre peut le prendre en utilisant les clés privées imprimées ici.

[WARNING]
====
N'ENVOYEZ D'ARGENT A AUCUNE DES ADRESSES DANS CE LIVRE. Votre argent sera pris par un autre lecteur, ou perdu à jamais.
====

=== Apprentissage en ligne O'Reilly

[role = "ormenabled"]
[NOTE]
====
Depuis plus de 40 ans, pass:[<a href="http://oreilly.com" class="orm:hideurl"><em class="hyperlink">O'Reilly Media</em></a>] fournit des formations, des connaissances et des perspectives en technologies et affaires pour aider les entreprises à réussir.
====

Notre réseau unique d'experts et d'innovateurs partagent leurs connaissances et leur expertise à travers des livres, des articles et notre plateforme d'apprentissage en ligne. La plateforme d'apprentissage en ligne O'Reilly vous donne un accès à la demande à des cours de formation en direct, des parcours d'apprentissage approfondis, des environnements de codage interactifs et une vaste collection de textes et de vidéos O'Reilly et de plus de 200 autres éditeurs. Pour plus d'informations, visitez pass:[<a href="http://oreilly.com" class="orm:hideurl"><em>http://oreilly.com</em></a>].

[[how_to_contact_us_sec]]
=== Comment nous contacter

Des informations sur _Maîtriser le Lightning Network_ ainsi que sur l'Open Edition et les traductions sont disponibles sur  link:$$https://lnbook.info$$[].

Veuillez adresser vos commentaires et questions concernant ce livre à l'éditeur :

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (aux États-Unis ou au Canada)</li>
  <li>707-829-0515 (international ou local)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

E-mail pass:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>] pour commenter ou poser des questions techniques sur ce livre.

Pour des nouvelles et des informations sur nos livres et nos cours, visitez le link:$$http://oreilly.com$$[].

Retrouvez-nous sur Facebook : link:$$http://facebook.com/oreilly$$[]

Suivez-nous sur Twitter : link:$$http://twitter.com/oreillymedia$$[]

Regardez-nous sur YouTube : link:$$http://www.youtube.com/oreillymedia$$[]

==== Contacter Andreas

Vous pouvez contacter Andreas M. Antonopoulos sur son site personnel :
link:$$https://aantonop.com$$[]

Abonnez-vous à la chaîne d'Andreas sur YouTube :
link:$$https://www.youtube.com/aantonop$$[]

Likez la page d'Andreas sur Facebook :
link:$$https://www.facebook.com/AndreasMAntonopoulos$$[]

Suivez Andreas sur Twitter :
link:$$https://twitter.com/aantonop$$[]

Connectez-vous avec Andreas sur LinkedIn :
link:$$https://linkedin.com/company/aantonop$$[]

Andreas tient également à remercier les mécènes qui soutiennent son travail par des dons mensuels. Vous pouvez soutenir Andreas sur Patreon sur link:$$https://patreon.com/aantonop$$[].

==== Contacter René

Vous pouvez contacter René Pickhardt sur son site personnel :
link:$$https://ln.rene-pickhardt.de$$[]

Abonnez-vous à la chaîne de René sur YouTube :
link:$$https://www.youtube.com/user/RenePickhardt$$[]

Suivez René sur Twitter :
link:$$https://twitter.com/renepickhardt$$[]

Connectez-vous avec René sur LinkedIn :
link:$$https://www.linkedin.com/in/rene-pickhardt-80313744$$[]

René tient également à remercier tous les mécènes qui soutiennent son travail par des dons mensuels. Vous pouvez soutenir René sur Patreon sur link:$$https://patreon.com/renepickhardt$$[].

Ou vous pouvez soutenir son travail directement avec Bitcoin (également via le Lightning Network) sur link:$$https://donate.ln.rene-pickhardt.de$$[] ce pourquoi René est tout aussi reconnaissant que pour ses mécènes Patreon.

==== Contacter Olaoluwa Osuntokun

Vous pouvez contacter Olaoluwa Osuntokun à son adresse e-mail professionnelle :
__laolu@lightning.engineering__

Suivez Olaoluwa sur Twitter :
link:$$https://twitter.com/roasbeef$$[]

[[acknowledgments_sec]]
=== Remerciements d'Andreas

Je dois mon amour des mots et des livres à ma mère, Theresa, qui m'a élevé dans une maison avec des livres tapissant tous les murs. Ma mère m'a également acheté mon premier ordinateur en 1982, bien qu'elle se décrive comme une technophobe. Mon père, Menelaos, un ingénieur civil qui a publié son premier livre à 80 ans, est celui qui m'a enseigné la pensée logique et analytique et l'amour de la science et de l'ingénierie.

Merci à tous de m'avoir soutenu tout au long de ce parcours.

=== Remerciements de René

Je tiens à remercier le système éducatif allemand grâce auquel j'ai acquis les connaissances sur lesquelles s'appuie mon travail. C'est l'un des plus beaux cadeaux que j'ai reçus.
De même, je tiens à remercier le système de santé public allemand et chaque personne qui consacre son temps à travailler au sein de cette industrie. Vos efforts et votre endurance font de vous mes héros personnels et je n'oublierai jamais l'aide, la patience et le soutien que j'ai reçus lorsque j'en avais besoin.
Merci à tous les étudiants auprès desquels j'ai été autorisé à enseigner et qui se sont engagés dans des discussions et des questions intéressantes. C'est de vous que j'ai le plus appris.
Je suis également reconnaissant aux communautés Bitcoin et Lightning Network qui m'ont chaleureusement accueilli et aux passionnés et particuliers qui ont soutenu financièrement et continuent de soutenir mon travail.
En particulier, je suis reconnaissant envers tous les développeurs open source (pas seulement Bitcoin et Lightning Network) et aux personnes qui les financent pour rendre ces technologies possibles.
Un merci spécial à mes coauteurs pour avoir roulé avec moi à travers la tempête.
Enfin et surtout, je suis reconnaissant envers mes proches.

=== Remerciements d'Olaoluwa Osuntokun

J'aimerais remercier l'incroyable équipe de Lightning Labs, car sans vous tous, il n'y
aurait pas de LND. Je voudrais également remercier le groupe original des auteurs de spécifications BOLT :
Rusty Russell, Fabrice Drouin, Conner Fromnkchet, Pierre-Marie
Padiou, Lisa Neigut et Christian Decker. Enfin et surtout, je voudrais
remercier Joseph Poon et Tadge Dryja, les auteurs originaux du papier Lightning
Network, car sans eux, il n'y aurait pas de Lightning Network sur lequel écrire
un livre.

[[github_contrib]]
=== Contributions

De nombreux contributeurs ont proposé des commentaires, des corrections et des ajouts au livre lorsqu'il a été écrit de manière collaborative sur GitHub.

Voici une liste triée par ordre alphabétique de tous les contributeurs GitHub, y compris leurs identifiants GitHub entre parenthèses :

include::github_contributors.asciidoc[]

Sans l'aide offerte par toutes les personnes énumérées ici, ce livre n'aurait pas été possible. Vos contributions démontrent la puissance de l'open source et de la culture ouverte, et nous sommes éternellement reconnaissants pour votre aide.

Merci.

=== Sources

Une partie du contenu de ce livre provient de diverses sources du domaine public, de sources de licences ouvertes ou avec autorisation. Voir <<sources_licenses>> pour les détails de sources, de licences et d'attributions.


