[appendix]
[[sources_licenses]]
== Sources et mentions de licence

Cette annexe contient des mentions d'attribution et de licence pour le matériel inclus avec l'autorisation accordée via des licences ouvertes.

=== Sources

Le matériel provient de diverses sources publiques et sous licence ouverte :

* https://wiki.ion.radar.tech[Wiki du Lightning Network ION]
* https://medium.com/suredbits/lightning-101-what-is-a-lightning-invoice-d527db1a77e6["Lightning 101: What Is a Lightning Invoice?" par Suredbits]
* https://github.com/lightningnetwork/lightning-rfc[Spécifications Lightning Network en cours GitHub]; Creative Commons Attribution (CC-BY 4.0)
* https://w.wiki/4QCL[Page Wikipédia, "Elliptic-curve Diffie–Hellman"]
* https://w.wiki/4QCX[Page Wikipédia, "Digital signature"]
* https://w.wiki/4QCb[Page Wikipédia, "Cryptographic hash function"]
* https://w.wiki/4QCc[Page Wikipédia, "Onion routing"]
* https://w.wiki/4QCd[Wikimedia Commons, "Lightning Network Protocol Suite"]
* https://w.wiki/4QCf[Wikimedia Commons, "Introduction to the Lightning Network Protocol and the Basics of Lightning Technology"]

[role="pagebreak-before less_space"]
=== BTCPay Server

BTCPay Server https://github.com/btcpayserver/btcpayserver-media[logo, captures d'écran et autres images] utilisés avec autorisation sous la https://github.com/btcpayserver/btcpayserver-media/blob/master/LICENSE[MIT License]:

[quote]
____
MIT License

Copyright (c) 2018 BTCPay Server

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
____

=== Lamassu Industries AG

Images du https://lamassu.is/product/gaia[_Gaia_ Bitcoin ATM] vu dans <<bitcoin-atm>> sont utilisés avec l'autorisation de Lamassu Industries AG. L'utilisation de ces images n'est pas une approbation du produit ou de l'entreprise, mais est fournie comme un exemple visuel d'un guichet automatique Bitcoin.
