title: "Maîtriser le Lightning Network"
author:
  name: Serafim Dos Santos
  email: info@maitriser.ca
description: >- # this means to ignore newlines until "baseurl:"
  Le livre Maîtriser le Lightning Network (Mastering the Lightning Network par O'Reilly Media) tel qu'écrit originalement en anglais par Andreas M. Antonopoulos, Olaoluwa Osuntokun et Rene Pickhardt traduit en français (Canada) par Google Translate API et révisé par Serafim Dos Santos avec les termes du Grand dictionnaire terminologique (GDT) de l'Office québécois de la langue française. La source de ce document peut-être téléchargé sur le site de GitHub au https://github.com/maitriser-ca/LivreLeLightningNetwork.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lightning.maitriser.ca" # the base hostname & protocol for your site, e.g. http://example.com
social_links:
    twitter: serafdossantos
    github:  SerafDosSantos

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

show_excerpts: true # set to true to show excerpts on the homepage
