source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
gem "liquid", ">= 4.0.4", "< 5.0"

gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.7"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
